<?php

if (!defined('ABSPATH'))
    die('-1');

return [
    'name' => __('Liwa Tilt Image', 'liwadates'),
    'description' => __('An image with interactive tilt effect on mouse hover', 'liwadates'),
    'base' => 'liwa_tilt_image',
    'icon' => 'icon-wpb-ui-image',
    'content_element' => true,
    'is_container' => false,
    'show_settings_on_create' => false,
    'category' => 'Liwa Addons',
    'params' => [
        [
            'type' => 'attach_image',
            'heading' => __('Image', 'liwadates'),
            'param_name' => 'image',
            'description' => __('Select image to display', 'liwadates'),
            'group' => __('Image Settings', 'liwadates'),
        ],
        [
            'type' => 'dropdown',
            'heading' => __('Image Size', 'liwadates'),
            'param_name' => 'image_size',
            'value' => [
                __('Thumbnail', 'liwadates') => 'thumbnail',
                __('Medium', 'liwadates') => 'medium',
                __('Large', 'liwadates') => 'large',
                __('Full Size', 'liwadates') => 'full',
            ],
            'std' => 'large',
            'description' => __('Choose image size', 'liwadates'),
            'group' => __('Image Settings', 'liwadates'),
        ],
        [
            'type' => 'textfield',
            'heading' => __('Image Alt Text', 'liwadates'),
            'param_name' => 'alt_text',
            'description' => __('Alternative text for the image (for accessibility)', 'liwadates'),
            'group' => __('Image Settings', 'liwadates'),
        ],
        [
            'type' => 'vc_link',
            'heading' => __('Image Link', 'liwadates'),
            'param_name' => 'image_link',
            'description' => __('Add link to the image (optional)', 'liwadates'),
            'group' => __('Image Settings', 'liwadates'),
        ],
        [
            'type' => 'dropdown',
            'heading' => __('Tilt Intensity', 'liwadates'),
            'param_name' => 'tilt_intensity',
            'value' => [
                __('Subtle', 'liwadates') => 'subtle',
                __('Normal', 'liwadates') => 'normal',
                __('Strong', 'liwadates') => 'strong',
            ],
            'std' => 'normal',
            'description' => __('Choose tilt effect intensity', 'liwadates'),
            'group' => __('Tilt Effects', 'liwadates'),
        ],
        [
            'type' => 'textfield',
            'heading' => __('Tilt Scale', 'liwadates'),
            'param_name' => 'tilt_scale',
            'value' => '1.05',
            'description' => __('Scale factor on hover (e.g., 1.05 for 5% larger)', 'liwadates'),
            'group' => __('Tilt Effects', 'liwadates'),
        ],
        [
            'type' => 'textfield',
            'heading' => __('Max Tilt Angle', 'liwadates'),
            'param_name' => 'max_tilt',
            'value' => '15',
            'description' => __('Maximum tilt angle in degrees (1-30)', 'liwadates'),
            'group' => __('Tilt Effects', 'liwadates'),
        ],
        [
            'type' => 'checkbox',
            'heading' => __('Enable Glow Effect', 'liwadates'),
            'param_name' => 'enable_glow',
            'value' => ['yes' => __('Yes', 'liwadates')],
            'description' => __('Add a glow effect on hover', 'liwadates'),
            'group' => __('Tilt Effects', 'liwadates'),
        ],
        [
            'type' => 'checkbox',
            'heading' => __('Enable Shadow Effect', 'liwadates'),
            'param_name' => 'enable_shadow',
            'value' => ['yes' => __('Yes', 'liwadates')],
            'description' => __('Add a shadow effect on hover', 'liwadates'),
            'group' => __('Tilt Effects', 'liwadates'),
        ],
        [
            'type' => 'dropdown',
            'heading' => __('Border Radius', 'liwadates'),
            'param_name' => 'border_radius',
            'value' => [
                __('None', 'liwadates') => 'none',
                __('Small', 'liwadates') => 'small',
                __('Rounded', 'liwadates') => 'rounded',
                __('Circle', 'liwadates') => 'circle',
            ],
            'std' => 'small',
            'description' => __('Choose border radius style', 'liwadates'),
            'group' => __('Appearance', 'liwadates'),
        ],
        [
            'type' => 'dropdown',
            'heading' => __('Theme', 'liwadates'),
            'param_name' => 'theme',
            'value' => [
                __('Default', 'liwadates') => 'default',
                __('Light', 'liwadates') => 'light',
                __('Dark', 'liwadates') => 'dark',
            ],
            'std' => 'default',
            'description' => __('Choose overlay theme', 'liwadates'),
            'group' => __('Appearance', 'liwadates'),
        ],
        [
            'type' => 'textfield',
            'heading' => __('Width', 'liwadates'),
            'param_name' => 'width',
            'description' => __('Image width (e.g., 300px, 50%, auto)', 'liwadates'),
            'group' => __('Dimensions', 'liwadates'),
        ],
        [
            'type' => 'textfield',
            'heading' => __('Height', 'liwadates'),
            'param_name' => 'height',
            'description' => __('Image height (e.g., 200px, auto)', 'liwadates'),
            'group' => __('Dimensions', 'liwadates'),
        ],
        [
            'type' => 'dropdown',
            'heading' => __('Alignment', 'liwadates'),
            'param_name' => 'alignment',
            'value' => [
                __('Left', 'liwadates') => 'left',
                __('Center', 'liwadates') => 'center',
                __('Right', 'liwadates') => 'right',
            ],
            'std' => 'center',
            'description' => __('Image alignment', 'liwadates'),
            'group' => __('Dimensions', 'liwadates'),
        ],
        [
            'type' => 'checkbox',
            'heading' => __('Animate on Scroll', 'liwadates'),
            'param_name' => 'animate_on_scroll',
            'value' => ['yes' => __('Yes', 'liwadates')],
            'description' => __('Add entrance animation when scrolling into view', 'liwadates'),
            'group' => __('Animation', 'liwadates'),
        ],
        [
            'type' => 'textfield',
            'heading' => __('Custom CSS Class', 'liwadates'),
            'param_name' => 'el_class',
            'description' => __('Add custom CSS class for additional styling', 'liwadates'),
            'group' => __('Advanced', 'liwadates'),
        ],
    ],
];
